### ISSUE TITLE
Steps to solving an (astro) SPH problem

### ISSUE THREAD

**Issue by LonelyCat124** [stfc/RegentParticleDSL#14]
List of issues that need solving to solve an astro SPH problem:

- [x] Complete the test example case.
- [x] Add a periodic neighbour search #9
- [x] Add a standard timestep loop #10
- [x] Choose an SPH kernel and implement the kernel function #11
- [x] Choose an SPH implementation and implement it #12
- [x] HDF5 IO reading/writing #13

Things I don't plan to do that are in SWIFT (from thinking last night, at least for now):
Multiple timestepping (i.e. particles that are not active in some steps)
Complex neighbour searching.

**Comment by LonelyCat124** [comment]
The hang also occurs on the so-called "blob test" around 1/10th the way in (1.090436 of 10 time units). I'm trying the perturbed box again now to see if it also hangs before its 1000 time unit end.

**Comment by LonelyCat124** [comment]
Ok, so there's a patch to resolve the hang now.

The SodShock now silenty fails after ~200 steps, which is about 2.5 hours. I'm trying a couple of things to see if I can see what the cause might be before having to enable debugging in Legion, as the duration of finding that cause is probably ~1 week runtime.

**Comment by LonelyCat124** [comment]
Have a perturbed box run submitted on scafellpike. Performance is likely to be poor (and physics inaccurate), but if it runs 24 hours I think this means this works.

**Comment by LonelyCat124** [comment]
Closing this issue as it "works", as in it works except the physics is wrong, which isn't my focus for now.
